name: Build project

on:
  push: 
    branches:
      - main
  workflow_dispatch:  

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps: 
    - name: buildstep1
      uses: actions/checkout@v4
    - name: setup for java
      uses: actions/checkout@v4
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
     - run: java HelloWorldApp.java
